version: "3.8"

services:
  web:
    build: .
    image: patrondiana13/todolist-dsti-devops:latest
    command: sh -c "sleep 3s && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - HOST=db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=supersecretpassword
