# Workflow for Continous Integration

name: Build and Test

# Controls when the action will run. Triggers the workflow on push or pull requests
# events only for the master branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# The workflow
jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate
        env:
          HOST: ${{secrets.HOST}}

      - name: Run tests
        run: python manage.py test
        env:
          HOST: ${{secrets.HOST}}
