---
- name: ensure apt cache is up to date
  apt: update_cache=yes

- name: ensure packages are installed
  apt:
    name: '{{item}}'
  loop:
    - postgresql
    - postgresql-contrib
    - git
    - libpq-dev
    - python-psycopg2
    - python3-dev
    - python-dev
    - python3-venv

- name: ensure the PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: ensure database is created
  become_user: postgres
  postgresql_db:
    name: todo_proj

- name: create a PostgreSQL user for this project
  become: true
  become_user: postgres
  postgresql_user:
    db: todo_proj
    name: todouser
    password: supersecretpassword
    priv: ALL
  notify:
    - restart postgresql

- name: create virtualenv
  command: python3 -m venv /home/vagrant/venv

- name: install requirements
  pip:
    requirements: /home/vagrant/todoproject/requirements.txt
    executable: /home/vagrant/venv/bin/pip

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: /home/vagrant/todoproject/
    virtualenv: /home/vagrant/venv
    settings: todoproject.settings
