---
- name: Update apt
  apt: update_cache=yes

- name: Install packages
  apt:
    name: '{{item}}'
  loop:
    - postgresql
    - postgresql-contrib
    - git
    - libpq-dev
    - python-psycopg2
    - python3-dev
    - python-dev
    - python3-venv

- name: Start postgreSQL service
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create database
  become_user: postgres
  postgresql_db:
    name: todo_proj

- name: Create a PostgreSQL user for this project
  become: true
  become_user: postgres
  postgresql_user:
    db: todo_proj
    name: todouser
    password: supersecretpassword
    priv: ALL
  notify:
    - restart postgresql

- name: Create virtualenv
  command: python3 -m venv /home/vagrant/venv

- name: Install requirements from requirements.txt file
  pip:
    requirements: /home/vagrant/todoproject/requirements.txt
    executable: /home/vagrant/venv/bin/pip

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: /home/vagrant/todoproject/
    virtualenv: /home/vagrant/venv
    settings: todoproject.settings

- name: Get all static files
  django_manage:
    app_path: /home/vagrant/todoproject/
    command: collectstatic
    virtualenv: /home/vagrant/venv
  become: yes

- name: Runserver django in the background
  shell: nohup /home/vagrant/venv/bin/python /home/vagrant/todoproject/manage.py runserver 0.0.0.0:8000 &
  become: yes
